build:
	make --quiet -C PS2Mouse build
	make --quiet -C VMwareMouse build
	make --quiet -C VirtualBoxMouse build

clean:
	make -C PS2Mouse clean
	make -C VMwareMouse clean
	make -C VirtualBoxMouse clean
