name: Build OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildcompiler:
    name: Build Cross-Compiler & Toolchain
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Cache cross Folder
      id: cache-cross
      uses: actions/cache@v5
      with:
        path: tools/cross
        key: ${{ runner.os }}-cross-${{ hashFiles('tools/Makefile') }}

    - name: Prepare Environment for Dev Container
      run: |
        sudo mkdir -p /tmp/.X11-unix
        sudo mkdir -p /run/user/1000/pulse
        sudo touch /run/user/1000/pulse/native

    - name: Run make ci-setup in dev container
      if: steps.cache-cross.outputs.cache-hit != 'true'
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: |
          /usr/bin/make ci-setup

  compile:
    name: Build OS
    runs-on: ubuntu-latest
    needs: [buildcompiler]
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Cache cross Folder
      id: cache-cross
      uses: actions/cache@v5
      with:
        path: tools/cross
        key: ${{ runner.os }}-cross-${{ hashFiles('tools/Makefile') }}

    - name: Prepare Environment for Dev Container
      run: |
        sudo mkdir -p /tmp/.X11-unix
        sudo mkdir -p /run/user/1000/pulse
        sudo touch /run/user/1000/pulse/native

    - name: Build AMD64 Debug
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-amd64-debug

    - name: Build AMD64 Release
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-amd64-release

    - name: Build i386 Debug
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-i386-debug

    - name: Build i386 Release
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-i386-release

    - name: Build ARM Debug
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-arm-debug

    - name: Build ARM Release
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-arm-release

    - name: Build AArch64 Debug
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-aarch64-debug

    - name: Build AArch64 Release
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-aarch64-release

    - name: Build Prepare Archive
      if: always()
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: /usr/bin/make __ci-prepare-archive

    - name: Upload Artifact
      if: always()
      uses: actions/gitea-upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/
