name: Build OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildcompiler:
    name: Build Cross-Compiler & Toolchain
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Cache cross Folder
      id: cache-cross
      uses: actions/cache@v5
      with:
        path: tools/cross
        key: ${{ runner.os }}-cross-${{ hashFiles('tools/Makefile') }}

    - name: Required packages for building gcc & binutils
      if: steps.cache-cross.outputs.cache-hit != 'true'
      run: |
        apt-get -y install --no-install-recommends build-essential bison flex libgmp-dev libmpfr-dev texinfo file python3-dev

    - name: Required packages for building test apps in userspace
      if: steps.cache-cross.outputs.cache-hit != 'true'
      run: |
        apt-get -y install --no-install-recommends mingw-w64 libtool libltdl-dev

    - name: Required packages for building the OS and misc
      if: steps.cache-cross.outputs.cache-hit != 'true'
      run: |
        apt-get -y install --no-install-recommends grub2-common xorriso mtools grub-common grub-efi-amd64-bin grub-efi-amd64-signed grub-gfxpayload-lists grub-pc-bin grub-pc grub2-common pip cmake

    - name: autoconf_2.69
      if: steps.cache-cross.outputs.cache-hit != 'true'
      run: |
        wget https://launchpad.net/ubuntu/+archive/primary/+files/autoconf_2.69-11.1_all.deb -O /tmp/autoconf.deb && dpkg --force-all -i /tmp/autoconf.deb

    - name: automake-1.15.1
      if: steps.cache-cross.outputs.cache-hit != 'true'
      run: |
        wget https://ftp.gnu.org/gnu/automake/automake-1.15.1.tar.gz -O /tmp/automake.tar.gz && tar -xzf /tmp/automake.tar.gz -C /tmp && cd /tmp/automake-1.15.1 && ./configure && make && sudo make install

    - name: Run make ci-setup
      if: steps.cache-cross.outputs.cache-hit != 'true'
      run: |
        /usr/bin/make ci-setup

  compile:
    name: Build OS
    runs-on: ubuntu-latest
    needs: [buildcompiler]
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Cache cross Folder
      id: cache-cross
      uses: actions/cache@v5
      with:
        path: tools/cross
        key: ${{ runner.os }}-cross-${{ hashFiles('tools/Makefile') }}

    - name: Build AMD64 Debug
      if: always()
      run: /usr/bin/make __ci-amd64-debug

    - name: Build AMD64 Release
      if: always()
      run: /usr/bin/make __ci-amd64-release

    - name: Build i386 Debug
      if: always()
      run: /usr/bin/make __ci-i386-debug

    - name: Build i386 Release
      if: always()
      run: /usr/bin/make __ci-i386-release

    - name: Build ARM Debug
      if: always()
      run: /usr/bin/make __ci-arm-debug

    - name: Build ARM Release
      if: always()
      run: /usr/bin/make __ci-arm-release

    - name: Build AArch64 Debug
      if: always()
      run: /usr/bin/make __ci-aarch64-debug

    - name: Build AArch64 Release
      if: always()
      run: /usr/bin/make __ci-aarch64-release

    - name: Build Prepare Archive
      if: always()
      run: /usr/bin/make __ci-prepare-archive

    - name: Upload Artifact
      if: always()
      uses: christopherhx/gitea-upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/
