build:
	make --quiet -C AMDPCNET build
	make --quiet -C E1000 build
	make --quiet -C RTL8139 build
	make --quiet -C RTL8169 build

prepare:
	$(info Nothing to prepare)

clean:
	make --quiet -C AMDPCNET clean
	make --quiet -C E1000 clean
	make --quiet -C RTL8139 clean
	make --quiet -C RTL8169 clean
