build:
	make -C AMDPCNET build
	make -C IntelGigabit build
	make -C RTL8139 build
	make -C RTL8169 build

prepare:
	$(info Nothing to prepare)

clean:
	make -C AMDPCNET clean
	make -C IntelGigabit clean
	make -C RTL8139 clean
	make -C RTL8169 clean
