name: Deploy Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploydoc:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update System
        run: sudo apt update

      - name: Install Doxygen
        run: sudo apt -y install doxygen make

      - name: Generate Documentation
        run: make doxygen

      - name: Copy GitHub Pages Website
        run: cp -r tools/website/* doxygen-doc/

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doxygen-doc
